credentials:
  usernames:
    admin:
      email: admin@quantumalloc.com
      name: Admin
      password: 240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9
      role: admin
    analyst:
      email: analyst@quantumalloc.com
      name: Analyst
      password: 20249749412d73a3f5799f6f1dcf910e7b4aa3ce4de133b1f8a63c044792a4e9
      role: analyst
    imran:
      email: thoubicimran@gmail.com
      name: Imran
      password: 4dabce596999b3077f439a8540f8a013b872bc915b80a48aa5d9d7a75863dfea
      role: superuser
    sakthi:
      email: abcd@gmail.com
      name: sakthi
      password: 42aabf321a3e462721e53ba50b82761d6756146eb4ed886058a6b5e5f654c58a
      role: user
